const imageObjects = {
  sectionOne: [
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=00FFFF&width=1920&height=1080&text=Hello",
      offsetX: 0,
      offsetY: 100,
      parallex: 3,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=00FFFF&width=1920&height=1080&text=Hello",
      offsetX: 100,
      offsetY: 150,
      parallex: 2,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=000000&width=1920&height=1080&text=Hello",
      offsetX: 100,
      offsetY: 100,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 300,
      offsetY: 150,
      parallex: 2,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=0000FF&width=1920&height=1080&text=Hello",
      offsetX: 350,
      offsetY: 0,
      parallex: 2,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=7393B3&width=1920&height=1080&text=Hello",
      offsetX: 120,
      offsetY: 75,
      parallex: 1,
    },
  ],
  sectionTwo: [
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=000000&width=1920&height=1080&text=Hello",
      offsetX: 50,
      offsetY: 50,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=000000&width=1920&height=1080&text=Hello",
      offsetX: 100,
      offsetY: 30,
      parallex: 2,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=000000&width=1920&height=1080&text=Hello",
      offsetX: 150,
      offsetY: 50,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=000000&width=1920&height=1080&text=Hello",
      offsetX: 200,
      offsetY: 50,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=000000&width=1920&height=1080&text=Hello",
      offsetX: 50,
      offsetY: 10,
      parallex: 21,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=000000&width=1920&height=1080&text=Hello",
      offsetX: 120,
      offsetY: 40,
      parallex: 2,
    },
  ],
  sectionThree: [
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=00FFFF&width=1920&height=1080&text=Hello",
      offsetX: 250,
      offsetY: 0,
      parallex: 3,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=F0FFFF&width=1920&height=1080&text=Hello",
      offsetX: 500,
      offsetY: 0,
      parallex: 2,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 750,
      offsetY: 0,
      parallex: 4,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=0000FF&width=1920&height=1080&text=Hello",
      offsetX: 1000,
      offsetY: 0,
      parallex: 2,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=7393B3&width=1920&height=1080&text=Hello",
      offsetX: 1250,
      offsetY: 0,
      parallex: 1,
    },
  ],
  sectionFour: [
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=00FFFF&width=1920&height=1080&text=Hello",
      offsetX: 150,
      offsetY: 50,
      parallex: 2,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=F0FFFF&width=1920&height=1080&text=Hello",
      offsetX: 50,
      offsetY: 100,
      parallex: 3,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 200,
      offsetY: 20,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=0000FF&width=1920&height=1080&text=Hello",
      offsetX: 200,
      offsetY: 100,
      parallex: 3,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=7393B3&width=1920&height=1080&text=Hello",
      offsetX: 50,
      offsetY: 50,
      parallex: 2,
    },
  ],
  sectionFive: [
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=00FFFF&width=1920&height=1080&text=Hello",
      offsetX: 50,
      offsetY: 100,
      parallex: 3,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=F0FFFF&width=1920&height=1080&text=Hello",
      offsetX: 50,
      offsetY: 20,
      parallex: 2,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 40,
      offsetY: 50,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=0000FF&width=1920&height=1080&text=Hello",
      offsetX: 100,
      offsetY: 150,
      parallex: 2,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=7393B3&width=1920&height=1080&text=Hello",
      offsetX: 250,
      offsetY: 10,
      parallex: 3,
    },
  ],
  sectionSix: [
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=00FFFF&width=1920&height=1080&text=Hello",
      offsetX: 250,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=F0FFFF&width=1920&height=1080&text=Hello",
      offsetX: 500,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 750,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=0000FF&width=1920&height=1080&text=Hello",
      offsetX: 1000,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=7393B3&width=1920&height=1080&text=Hello",
      offsetX: 1250,
      offsetY: 0,
      parallex: 1,
    },
  ],
  sectionSeven: [
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=00FFFF&width=1920&height=1080&text=Hello",
      offsetX: 200,
      offsetY: 100,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=F0FFFF&width=1920&height=1080&text=Hello",
      offsetX: 100,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 150,
      offsetY: 50,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=0000FF&width=1920&height=1080&text=Hello",
      offsetX: 200,
      offsetY: 300,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=7393B3&width=1920&height=1080&text=Hello",
      offsetX: 250,
      offsetY: 1000,
      parallex: 1,
    },
  ],
  sectionEight: [
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=00FFFF&width=1920&height=1080&text=Hello",
      offsetX: 250,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 500,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 750,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 1000,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 1250,
      offsetY: 0,
      parallex: 1,
    },
  ],
  sectionNine: [
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=00FFFF&width=1920&height=1080&text=Hello",
      offsetX: 250,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=F0FFFF&width=1920&height=1080&text=Hello",
      offsetX: 500,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=89CFF0&width=1920&height=1080&text=Hello",
      offsetX: 750,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=0000FF&width=1920&height=1080&text=Hello",
      offsetX: 1000,
      offsetY: 0,
      parallex: 1,
    },
    {
      url: "https://www.colorbook.io/imagecreator.php?hex=7393B3&width=1920&height=1080&text=Hello",
      offsetX: 1250,
      offsetY: 0,
      parallex: 1,
    },
  ],
};
